name: jellyfinmediaplayer
base: core22
version: '1.11.1'
summary: Jellyfin Desktop Client based on Plex Media Player
description: |
  Desktop client using jellyfin-web with embedded MPV player. Media plays within the same window using the jellyfin-web interface unlike Jellyfin Desktop. Supports audio passthrough. Based on Plex Media Player.
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64

apps:
  jellyfinmediaplayer:
    command: usr/bin/jellyfinmediaplayer
    desktop: usr/share/applications/com.github.iwalton3.jellyfin-media-player.desktop
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - screen-inhibit-control
      - network
      - shmem
      - home
      
plugs:
  shmem:
    interface: shared-memory
    private: true

environment:
  QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}
  QML2_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml:$SNAP/lib/$CRAFT_ARCH_TRIPLET:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml:$SNAP_DESKTOP_RUNTIME/lib/$CRAFT_ARCH_TRIPLET${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}
  LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/lapack${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  QTWEBENGINEPROCESS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/libexec/QtWebEngineProcess
  DISABLE_WAYLAND: 1

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5
  /usr/share/jellyfinmediaplayer:
    bind: $SNAP/usr/share/jellyfinmediaplayer

parts:
  jellyfinmediaplayer:
    plugin: dump
    source: https://github.com/jellyfin/jellyfin-media-player/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/jellyfin-media-player_${SNAPCRAFT_PROJECT_VERSION}-1_amd64-jammy.deb
    source-type: deb
    stage-packages:
      - libmpv1
      - libqt5webengine5
      - libcec6
      - qml-module-qtwebengine
      - qml-module-qtwebchannel
      - qml-module-qtquick-controls
      - libqt5x11extras5
      - libqt5xml5
      - libqt5webenginecore5
      - libblas3
      - liblapack3
    override-build: |
      craftctl default
      sed -i 's|Icon=com.github.iwalton3.jellyfin-media-player|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.iwalton3.jellyfin-media-player.svg|' ${CRAFT_PART_INSTALL}/usr/share/applications/com.github.iwalton3.jellyfin-media-player.desktop

  cleanup:
    after: [jellyfinmediaplayer]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
      
